# Generated by Django 3.1.7 on 2021-04-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicquiz', '0003_comment_musiccategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiccategory',
            name='image_path',
            field=models.CharField(default='/media/category_images\\sip.jpg', max_length=200),
        ),
    ]
