# Generated by Django 3.1.7 on 2021-04-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicquiz', '0004_musiccategory_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musiccategory',
            name='image_path',
        ),
        migrations.AddField(
            model_name='musiccategory',
            name='image_name',
            field=models.CharField(default='baby.jpg', max_length=200),
            preserve_default=False,
        ),
    ]
