# Generated by Django 3.1.7 on 2021-04-02 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicquiz', '0005_auto_20210401_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicquiz.musiccategory'),
        ),
    ]
